globals:
  base_path: https://raw.githubusercontent.com/sych74/wordpress-multiregion-standalone/master
  wp_cluster_path: https://raw.githubusercontent.com/sych74/wordpress-cluster/v2.2.0
  wp_standalone_path: https://raw.githubusercontent.com/sych74/wordpress/v2.2.0
  db_cluster_path: https://raw.githubusercontent.com/jelastic-jps/mysql-cluster/v2.4.1
